services:
  - type: web
    name: telegram-trading-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_final.py
    envVars:
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN_HERE